import { Password } from './types'

export const mockPasswords: Password[] = [
  {
    id: 'pwd-1',
    employee: 'Jason Lee',
    department: 'Finance',
    submitted: 'P@ssword2025',
    timestamp: '09:12 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 12 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains common word "password"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns detected', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns detected', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name or common personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-2',
    employee: 'Sarah Chen',
    department: 'Engineering',
    submitted: 'BlueMountain#847',
    timestamp: '09:45 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 14 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains common words "Blue" and "Mountain"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns detected', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns detected', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-3',
    employee: 'Michael Torres',
    department: 'Sales',
    submitted: 'qwerty123456',
    timestamp: '08:30 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 12 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Only contains lowercase and numbers', icon: 'Aa', present: false, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'No common dictionary words', icon: '📚', present: false, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'Contains sequential pattern "123456"', icon: '1️⃣', present: true, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'Contains keyboard pattern "qwerty"', icon: '⌨️', present: true, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Found in common passwords list', icon: '⚠️', present: true, checked: false, weight: 50 },
    ],
    correctDecision: 'reject',
  },
  {
    id: 'pwd-4',
    employee: 'Emily Watson',
    department: 'HR',
    submitted: 'Tr0pic@lSunset#92',
    timestamp: '07:30 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 16 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'No common dictionary words', icon: '📚', present: false, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'approve',
  },
  {
    id: 'pwd-5',
    employee: 'David Kim',
    department: 'Engineering',
    submitted: 'DavidKim2024!',
    timestamp: '06:45 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 13 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains employee name "David" and "Kim"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Contains employee name', icon: '👤', present: true, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-6',
    employee: 'Rachel Green',
    department: 'Marketing',
    submitted: 'X#9kL@mN2pQ$vW',
    timestamp: '05:15 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 14 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'No dictionary words', icon: '📚', present: false, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'approve',
  },
  {
    id: 'pwd-7',
    employee: 'James Rodriguez',
    department: 'Finance',
    submitted: 'welcome123',
    timestamp: '04:30 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 11 characters', icon: '📏', present: false, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Only lowercase and numbers', icon: 'Aa', present: false, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains dictionary word "welcome"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'Contains sequential pattern "123"', icon: '1️⃣', present: true, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Found in common passwords list', icon: '⚠️', present: true, checked: false, weight: 50 },
    ],
    correctDecision: 'reject',
  },
  {
    id: 'pwd-8',
    employee: 'Lisa Anderson',
    department: 'Operations',
    submitted: 'Phoenix@2026#Star',
    timestamp: '03:45 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 15 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains dictionary word "Phoenix" and "Star"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-9',
    employee: 'Chris Butler',
    department: 'Sales',
    submitted: 'MyP@ssw0rd!Secure',
    timestamp: '02:30 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 17 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains "password" and "secure"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Found in common passwords list', icon: '⚠️', present: true, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-10',
    employee: 'Nina Patel',
    department: 'Engineering',
    submitted: 'Quantum$Leap#89X',
    timestamp: '01:15 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 15 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains words but unique combination', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'approve',
  },
  {
    id: 'pwd-11',
    employee: 'Marcus Johnson',
    department: 'IT',
    submitted: 'admin123admin',
    timestamp: '12:00 AM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 13 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Only lowercase and numbers', icon: 'Aa', present: false, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains dictionary word "admin"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'Contains sequential pattern "123"', icon: '1️⃣', present: true, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Found in common passwords list', icon: '⚠️', present: true, checked: false, weight: 50 },
    ],
    correctDecision: 'reject',
  },
  {
    id: 'pwd-12',
    employee: 'Sandra Lee',
    department: 'HR',
    submitted: 'GoldenHour@2026#',
    timestamp: '11:00 PM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 15 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains words "Golden" and "Hour"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain employee name', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-13',
    employee: 'Trevor White',
    department: 'Operations',
    submitted: 'Tr3v0r@White$24',
    timestamp: '10:00 PM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 15 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains employee name parts', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Contains employee name', icon: '👤', present: true, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'revision',
  },
  {
    id: 'pwd-14',
    employee: 'Olivia Martinez',
    department: 'Finance',
    submitted: 'Cr1mson#Sky@925!',
    timestamp: '09:00 PM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 16 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains words but unique', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'No sequential patterns', icon: '1️⃣', present: false, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Not in known breach database', icon: '⚠️', present: false, checked: false, weight: 50 },
    ],
    correctDecision: 'approve',
  },
  {
    id: 'pwd-15',
    employee: 'Kevin Stewart',
    department: 'Marketing',
    submitted: 'Test@1234pass',
    timestamp: '08:00 PM',
    characteristics: [
      { id: 'length', label: 'Minimum 12 characters', description: 'Has 13 characters', icon: '📏', present: true, checked: false, weight: 50 },
      { id: 'diversity', label: 'Character Diversity', description: 'Contains uppercase, lowercase, numbers, and symbols', icon: 'Aa', present: true, checked: false, weight: 30 },
      { id: 'dictionary', label: 'Dictionary Words', description: 'Contains "Test" and "pass"', icon: '📚', present: true, checked: false, weight: 20 },
      { id: 'sequential', label: 'Sequential Numbers', description: 'Contains sequential pattern "1234"', icon: '1️⃣', present: true, checked: false, weight: 25 },
      { id: 'keyboard', label: 'Keyboard Patterns', description: 'No keyboard patterns', icon: '⌨️', present: false, checked: false, weight: 25 },
      { id: 'personal', label: 'Personal Information', description: 'Does not contain personal info', icon: '👤', present: false, checked: false, weight: 20 },
      { id: 'company', label: 'Company Name', description: 'Does not contain company name', icon: '🏢', present: false, checked: false, weight: 20 },
      { id: 'leaked', label: 'Known Leaked Passwords', description: 'Found in common passwords list', icon: '⚠️', present: true, checked: false, weight: 50 },
    ],
    correctDecision: 'reject',
  },
]
