import { DataClassification } from './types'

export const mockDataClassifications: DataClassification[] = [
  {
    id: 'doc-1',
    title: 'Q3 Marketing Plan',
    from: 'Marketing Team',
    timestamp: '09:00 AM',
    fileType: 'PDF',
    fileSize: '1.2 MB',
    preview: 'Q3_Marketing_Plan.pdf\n\nThis document contains our quarterly marketing strategy, campaign timelines, and budget allocations for Q3 2026. It outlines our approach to promoting new product launches and market expansion in key regions.',
    sensitivityIndicators: [
      'Strategic business plans',
      'Budget information',
      'Market expansion data',
      'Product launch details',
    ],
    correctClassification: 'internal',
    shouldShareWith: 'External Marketing Agency',
  },
  {
    id: 'doc-2',
    title: 'Employee Handbook',
    from: 'Human Resources',
    timestamp: '08:15 AM',
    fileType: 'DOCX',
    fileSize: '2.5 MB',
    preview: 'Employee_Handbook_2026.docx\n\nCompany policies, code of conduct, benefits information, vacation policies, and general employee guidelines. This document is distributed to all employees on their first day.',
    sensitivityIndicators: [
      'Company policies',
      'Employee guidelines',
      'Publicly distributed document',
    ],
    correctClassification: 'internal',
    shouldShareWith: 'All Employees',
  },
  {
    id: 'doc-3',
    title: 'Customer Database Export',
    from: 'Database Admin',
    timestamp: '07:45 AM',
    fileType: 'CSV',
    fileSize: '45 MB',
    preview: 'customer_database_2026.csv\n\nContains customer names, email addresses, phone numbers, home addresses, purchase history, credit card last 4 digits, and customer lifetime value. Records for 50,000+ customers.',
    sensitivityIndicators: [
      'Personally Identifiable Information (PII)',
      'Customer names and contact information',
      'Customer financial data',
      'Email addresses and phone numbers',
      'Home addresses',
      'Purchase history',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'Authorized Data Team Members Only',
  },
  {
    id: 'doc-4',
    title: 'API Keys and Credentials',
    from: 'IT Security',
    timestamp: '10:30 AM',
    fileType: 'TXT',
    fileSize: '50 KB',
    preview: 'prod_api_keys_2026.txt\n\nProduction API keys, database passwords, SSH keys, OAuth tokens, and authentication credentials for all company services including AWS, Firebase, and third-party APIs.',
    sensitivityIndicators: [
      'Authentication credentials',
      'API keys and tokens',
      'Database passwords',
      'SSH keys',
      'Production system access',
      'OAuth credentials',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'System Administrators Only',
  },
  {
    id: 'doc-5',
    title: 'Blog Post: Company Culture',
    from: 'Communications',
    timestamp: '11:00 AM',
    fileType: 'DOCX',
    fileSize: '500 KB',
    preview: 'Blog_Company_Culture.docx\n\nArticle intended for public blog about company culture, team building events, and employee success stories. No sensitive information included. Ready for publication on company website.',
    sensitivityIndicators: [
      'Intended for external publication',
      'Public company information',
      'Employee testimonials (public)',
    ],
    correctClassification: 'public',
    shouldShareWith: 'Public Website',
  },
  {
    id: 'doc-6',
    title: 'Board Meeting Minutes',
    from: 'Executive Office',
    timestamp: '09:30 AM',
    fileType: 'DOCX',
    fileSize: '1.1 MB',
    preview: 'Board_Minutes_Q2_2026.docx\n\nMinutes from quarterly board meeting including financial results, strategic decisions, acquisition discussions, executive compensation, and investor relations updates. Contains forward-looking business strategy.',
    sensitivityIndicators: [
      'Strategic business plans',
      'Financial information',
      'Executive compensation',
      'Acquisition details',
      'Confidential contracts',
      'Board-level decisions',
    ],
    correctClassification: 'confidential',
    shouldShareWith: 'Board Members and Senior Executives Only',
  },
  {
    id: 'doc-7',
    title: 'Press Release - New Product Launch',
    from: 'Communications',
    timestamp: '08:00 AM',
    fileType: 'DOCX',
    fileSize: '350 KB',
    preview: 'Press_Release_Product_Launch.docx\n\nPublic press release announcing our new product launch next quarter. Ready for distribution to media outlets and public announcement.',
    sensitivityIndicators: ['Intended for public distribution', 'Marketing materials'],
    correctClassification: 'public',
    shouldShareWith: 'Media and Public',
  },
  {
    id: 'doc-8',
    title: 'Employee Salary Records',
    from: 'Payroll Department',
    timestamp: '07:30 AM',
    fileType: 'XLSX',
    fileSize: '2.8 MB',
    preview: 'Payroll_Database_Q2_2026.xlsx\n\nComplete employee salary records including names, salary amounts, bonuses, tax withholdings, and direct deposit information for all 200+ employees.',
    sensitivityIndicators: [
      'Employee salary information',
      'Personal financial data',
      'Tax withholding details',
      'Direct deposit accounts',
      'Highly sensitive personal information',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'HR and Finance Executives Only',
  },
  {
    id: 'doc-9',
    title: 'Company Social Media Policy',
    from: 'HR Department',
    timestamp: '06:45 AM',
    fileType: 'PDF',
    fileSize: '1.5 MB',
    preview: 'Social_Media_Policy_2026.pdf\n\nCompany policy on employee use of social media, distributed to all employees during onboarding. Includes guidelines for posting about company.',
    sensitivityIndicators: ['Standard company policy', 'Distributed to all employees'],
    correctClassification: 'internal',
    shouldShareWith: 'All Employees',
  },
  {
    id: 'doc-10',
    title: 'Client Contract - Tech Solutions Inc',
    from: 'Legal Department',
    timestamp: '05:15 AM',
    fileType: 'PDF',
    fileSize: '850 KB',
    preview: 'Tech_Solutions_Contract_2026.pdf\n\nMulti-year contract with Tech Solutions Inc including pricing, service levels, payment terms, and confidentiality clauses. Contains sensitive commercial terms.',
    sensitivityIndicators: [
      'Client contracts',
      'Pricing information',
      'Service level agreements',
      'Confidential terms',
    ],
    correctClassification: 'confidential',
    shouldShareWith: 'Legal, Finance, and Account Managers Only',
  },
  {
    id: 'doc-11',
    title: 'Annual Sustainability Report',
    from: 'Operations',
    timestamp: '04:30 AM',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    preview: 'Sustainability_Report_2026.pdf\n\nAnnual sustainability and corporate responsibility report with environmental impact metrics, carbon footprint, and company initiatives. Published on company website.',
    sensitivityIndicators: ['Public company information', 'Published externally'],
    correctClassification: 'public',
    shouldShareWith: 'Public Website',
  },
  {
    id: 'doc-12',
    title: 'IT Security Incident Report',
    from: 'IT Security',
    timestamp: '03:45 AM',
    fileType: 'DOCX',
    fileSize: '1.8 MB',
    preview: 'Security_Incident_Report_2026.docx\n\nDetailed analysis of a data breach incident including vulnerability details, compromised systems, affected users, remediation steps, and security recommendations.',
    sensitivityIndicators: [
      'Security vulnerabilities',
      'Breach details',
      'System vulnerabilities',
      'Remediation strategies',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'Security Team and Executive Leadership Only',
  },
  {
    id: 'doc-13',
    title: 'Monthly Sales Report',
    from: 'Sales Department',
    timestamp: '02:30 AM',
    fileType: 'XLSX',
    fileSize: '1.2 MB',
    preview: 'Sales_Report_June_2026.xlsx\n\nMonthly sales figures, regional breakdown, customer acquisition data, and performance metrics shared within sales department.',
    sensitivityIndicators: ['Internal business metrics', 'Sales performance data'],
    correctClassification: 'internal',
    shouldShareWith: 'Sales Team and Management',
  },
  {
    id: 'doc-14',
    title: 'Vendor Payment Records',
    from: 'Finance',
    timestamp: '01:15 AM',
    fileType: 'XLSX',
    fileSize: '890 KB',
    preview: 'Vendor_Payments_2026.xlsx\n\nComplete vendor payment records including vendor names, addresses, account numbers, payment amounts, and banking information for 150+ vendors.',
    sensitivityIndicators: [
      'Financial information',
      'Vendor banking details',
      'Payment records',
      'Account information',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'Finance Department Only',
  },
  {
    id: 'doc-15',
    title: 'Industry Conference Brochure',
    from: 'Marketing',
    timestamp: '12:00 AM',
    fileType: 'PDF',
    fileSize: '2.1 MB',
    preview: 'Tech_Conference_2026_Brochure.pdf\n\nMarketing brochure for industry conference highlighting company services, team bios, and booth information. Distributed at conference and online.',
    sensitivityIndicators: ['Marketing material', 'Public distribution'],
    correctClassification: 'public',
    shouldShareWith: 'Conference Attendees and Public',
  },
]
